# Generated by Django 2.2.28 on 2023-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_dashboar_dm', '0002_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
