# Generated by Django 2.2.28 on 2023-05-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_dashboar_dm', '0003_article_test_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test_2',
        ),
    ]
